language: c

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - scons
      - check
      - python
      - libjansson-dev
      - libcurl3-openssl-dev

python:
  - "2.7"

before_install:
  - whereis clang
  - sudo apt-get update -qq
  - sudo apt-get install -y check scons python-virtualenv libjansson-dev libcurl4-openssl-dev clang
  - sudo apt-get autoremove
  - whereis clang
  - scons statsite test_runner
  - virtualenv ve

install: ve/bin/pip install pytest==2.3.4

script: ./test_runner && ve/bin/py.test integ
