language: c

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - check
      - clang
      - libjansson-dev
      - libcurl4-openssl-dev
      - python
      - python-virtualenv
      - scons

python:
  - "2.7"

before_install:
  - scons statsite test_runner
  - virtualenv ve

install: ve/bin/pip install pytest==2.3.4

script: ./test_runner && ve/bin/py.test integ
